### ISSUE TITLE
Documentation is ahead of the SDK implementation?

### ISSUE THREAD

**Issue by tomadamatkinson** [aws/amazon-chime-sdk-cpp#16]
The [API Overview](https://github.com/aws/amazon-chime-sdk-cpp/blob/main/guides/api_overview.md) looks to be ahead of the SDK implementation.

The overview mentions the `chime::ConsoleLogger`, the `Logger` interface and `MeetingSessionDependencies` which are not present in the `chime-sdk-signaling-cpp` folder.

Is there a newer version of the SDK which has not been published yet?

**Comment by hokyungh** [comment]
Hi sorry for the confusion on here, so there are currently two projects on this repo. 

1. Signaling SDK = Open sourced
2. Windows SDK = Closed sourced only release binary.

The API overview is for Windows CPP SDK. For signaling sdk api, refer to [here](https://github.com/aws/amazon-chime-sdk-cpp/tree/main/chime-sdk-signaling-cpp)

**Comment by tomadamatkinson** [comment]
Ah, this makes sense! Is there a reason why there is a discrepancy between the two SDKs?

**Comment by hokyungh** [comment]
so Windows SDK is actually standalone C++ SDK which incorporates our media layer, so with it, it doesn't require any dependencies. However, for signaling SDK, you will have to build and run your own webRTC.
