### ISSUE TITLE
facing issue while building Chime SDK for C++ Signaling Client Demo Application

### ISSUE THREAD

**Issue by janureka** [aws/amazon-chime-sdk-cpp#27]
when i try to build the application  i am getiing these errors mentined below(using ubuntu 22 version)
https://github.com/aws/amazon-chime-sdk-cpp/blob/main/chime-sdk-signaling-cpp/demo/cli/README.md

e-sdk-signaling-cpp$ cmake --build build
[ 21%] Built target libprotobuf
[ 21%] Built target GENHDR
[ 43%] Built target websockets
[ 46%] Built target amazon-chime-signaling-sdk-cpp-lib
[ 68%] Built target websockets_shared
[ 75%] Built target libprotobuf-lite
[ 96%] Built target libprotoc
[ 96%] Linking CXX executable protoc
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
libprotocd.a(cpp_helpers.cc.o): in function `google::protobuf::compiler::cpp::SetCommonVars(google::protobuf::compiler::cpp::Options const&, std::__Cr::map<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::less<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > >, std::__Cr::allocator<std::__Cr::pair<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > > > >*)':
cpp_helpers.cc:(.text+0xfb): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x104): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x16e): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x1ca): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x22c): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o):cpp_helpers.cc:(.text+0x254): more undefined references to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()' follow
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o): in function `google::protobuf::compiler::cpp::SetUnknkownFieldsVariable(google::protobuf::Descriptor const*, google::protobuf::compiler::cpp::Options const&, std::__Cr::map<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::less<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > >, std::__Cr::allocator<std::__Cr::pair<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > > > >*)':
cpp_helpers.cc:(.text+0x819): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > std::__Cr::operator+<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >(char const*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)'
/usr/bin/ld: cpp_helpers.cc:(.text+0x85b): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x867): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x881): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > std::__Cr::operator+<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >(char const*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)'
/usr/bin/ld: cpp_helpers.cc:(.text+0x92f): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x93b): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x947): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x953): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0x95f): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o):cpp_helpers.cc:(.text+0x98d): more undefined references to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()' follow
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o): in function `google::protobuf::compiler::cpp::SetUnknkownFieldsVariable(google::protobuf::Descriptor const*, google::protobuf::compiler::cpp::Options const&, std::__Cr::map<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, std::__Cr::less<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > >, std::__Cr::allocator<std::__Cr::pair<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > > > >*)':
cpp_helpers.cc:(.text+0xa72): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > std::__Cr::operator+<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >(char const*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)'
/usr/bin/ld: cpp_helpers.cc:(.text+0xb20): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0xb2c): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0xb38): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0xb44): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: cpp_helpers.cc:(.text+0xb50): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o):cpp_helpers.cc:(.text+0xba5): more undefined references to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()' follow
/usr/bin/ld: libprotocd.a(cpp_helpers.cc.o): in function `goo

.
.
.
.
.
.

usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
libprotobufd.a(implicit_weak_message.cc.o): in function `google::protobuf::internal::ImplicitWeakMessage::~ImplicitWeakMessage()':
implicit_weak_message.cc:(.text._ZN6google8protobuf8internal19ImplicitWeakMessageD2Ev[_ZN6google8protobuf8internal19ImplicitWeakMessageD2Ev]+0x27): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: libprotobufd.a(implicit_weak_message.cc.o): in function `google::protobuf::internal::EpsCopyInputStream::AppendString(char const*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >*)::{lambda(char const*, long)#1}::operator()(char const*, long) const':
implicit_weak_message.cc:(.text._ZZN6google8protobuf8internal18EpsCopyInputStream12AppendStringEPKcPNSt4__Cr12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEENKUlS4_lE_clES4_l[_ZZN6google8protobuf8internal18EpsCopyInputStream12AppendStringEPKcPNSt4__Cr12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEENKUlS4_lE_clES4_l]+0x24): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::append(char const*, unsigned long)'
/usr/bin/ld: libprotobufd.a(implicit_weak_message.cc.o): in function `void std::__Cr::call_once<void (&)()>(std::__Cr::once_flag&, void (&)())':
implicit_weak_message.cc:(.text._ZNSt4__Cr9call_onceIRFvvEJEEEvRNS_9once_flagEOT_DpOT0_[_ZNSt4__Cr9call_onceIRFvvEJEEEvRNS_9once_flagEOT_DpOT0_]+0x49): undefined reference to `std::__Cr::__call_once(unsigned long volatile&, void*, void (*)(void*))'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
libprotobufd.a(any.cc.o): in function `google::protobuf::internal::AnyMetadata::PackFrom(google::protobuf::Message const&)':
any.cc:(.text+0x4c): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: any.cc:(.text+0x67): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: libprotobufd.a(any.cc.o): in function `google::protobuf::internal::AnyMetadata::PackFrom(google::protobuf::Message const&, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > const&)':
any.cc:(.text+0x10e): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
/usr/bin/ld: any.cc:(.text+0x169): undefined reference to `std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >::~basic_string()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [_deps/protobuf-build/CMakeFiles/protoc.dir/build.make:100: _deps/protobuf-build/protoc-3.13.0.0] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1530: _deps/protobuf-build/CMakeFiles/protoc.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2

**Comment by hensmi-amazon** [comment]
Hi can you retry following my latest commit and README changes?

**Comment by georgezy-amzn** [comment]
This issue has been fixed with PR #29 on Aug 9. Please reopen or submit a support case if this is still an issue.
