### ISSUE TITLE
How to build amazon chime sdk on Windows using VS code

### ISSUE THREAD

**Issue by anjalipillai09** [aws/amazon-chime-sdk-cpp#32]
I want to build the amazon chime sdk on windows using Visual Studio Code. Could you please provide the steps for the same.

**Comment by hensmi-amazon** [comment]
Hello. VS Code is not really a build system, though it does [integrate well with CMake](https://code.visualstudio.com/docs/cpp/cmake-linux), which we recommend to use when starting a project from scratch.

**Comment by anjalipillai09** [comment]
Hello
Tried to integrating using CMake but was not able to configure due to openssl libraries. For your reference I have added the screenshot
![image](https://github.com/user-attachments/assets/c87caa34-6cb8-45cb-945c-27af9741e71d)

**Comment by hensmi-amazon** [comment]
What platform are you running on? Have you installed openssl? If it is not in `/usr/lib/` and `/usr/include/`, you need to set `-DLWS_OPENSSL_LIBRARIES` and `-DLWS_OPENSSL_INCLUDE_DIRS` as mentioned in README.

**Comment by anjalipillai09** [comment]
Running on windows and openssl is installed
![image](https://github.com/user-attachments/assets/f3819452-e691-4c0f-b6fe-0b3c9b188c81)

**Comment by hensmi-amazon** [comment]
Openssl may be installed, but it is probably not in the location checked by CMake. Please find the locations of libssl.so and set the values `LWS_OPENSSL_LIBRARIES` and `LWS_OPENSSL_INCLUDE_DIRS`

**Comment by hensmi-amazon** [comment]
Closing due to age.
