### ISSUE TITLE
When receiving MediaMetrics, the RemoteVideoMetrics are always empty

### ISSUE THREAD

**Issue by StefH** [aws/amazon-chime-sdk-cpp#33]
### Is this an issue with the Amazon Chime SDK for C++ or with the Amazon Chime SDK for C++ Signaling Client?

ChimeSdk-0.11.0-20240530-Windows-Release

### What happened and what did you expect to happen?

When calling `.DebugString()` on `MediaMetrics`, I would expect that also the RemoteVideoMetrics would be logged but only GlobalMetrics, LocalAudioMetrics and RemoteAudioMetrics are logged.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-cpp/issues)

### Reproduction steps

On a started meeting session attach an AudioVideoObserver:
``` c++
_meetingSession->audio_video->AddAudioVideoObserver(...);
```

Callback method:
``` c++
void OnMediaMetrics(const chime::MediaMetrics& metrics) override
{
	LOGMSG << "OnMediaMetrics():" << metrics.DebugString();
};
```

And then the attendee starts the video or starts sharing the screen, all media metrics should be received.

https://github.com/aws/amazon-chime-sdk-cpp/blob/main/guides/api_overview.md#9-receive-media-metrics

### Library version

ChimeSdk-0.11.0-20240530-Windows-Release

### Meeting and Attendee ID Information.

46d78c4d-0f1d-4cbe-8d79-db6229472c6b / 6014ca60-e827-40ea-a707-969f7a087979

### Client logs

Only **global_metrics**, **local_audio_metrics** and **remote_audio_metrics** are logged. The **remote_video_metrics** are missing.

```
{ global_metrics: { metrics: { AvailableReceiveBandwidth: 2800000.000000} { AvailableSendBandwidth: 5616000.000000} }, local_audio_metrics: { metrics: { PacketsSent: 0.000000} { BytesSent: 0.000000} } , remote_audio_metrics: { metrics: { PacketsReceived: 49.950050} { BytesReceived: 1648.351648} { Jitter: 0.000000} { JitterBufferDelay: 0.000000} } }
```

**Comment by hensmi-amazon** [comment]
Thank you for the report. We have fixed the bug leading to these missing metrics and the fix will be in the next release (should be about a month).

**Comment by StefH** [comment]
Thanks for foxing the bug, I'm looking forward to the release. Do you have a detailed ETA?

**Comment by hensmi-amazon** [comment]
We cannot guarantee a release. But you will see something like the following in the JS SDK repo: https://github.com/aws/amazon-chime-sdk-js/issues/2946 . If we do release, the timing will be similar.

**Comment by StefH** [comment]
@hensmi-amazon 
I can confirm that the RemoteVideoMetrics are present in the latest version (https://github.com/aws/amazon-chime-sdk-cpp/releases/tag/v0.11.1-cpp).
