### ISSUE TITLE
C++ Client Side SDK for Amazon Chime SDK

### ISSUE THREAD

**Issue by zhinang-amazon** [aws/amazon-chime-sdk-cpp#5]
As a customer, I would like to connect to Amazon Chime SDK meetings from a C++ environment. This can be used to send/receive media streams into Amazon Chime SDK meetings from embedded devices such as drones or IP cameras, or used as a media gateway to connect on-premise A/V system with remote meeting attendees.

**Comment by zhinang-amazon** [comment]
We have recently launched the[ signaling client ](https://github.com/aws/amazon-chime-sdk-cpp/tree/main/chime-sdk-signaling-cpp)component in this Amazon Chime SDK for C++ repo. There is also a CLI demo application that showcase how this signaling client can be used along side libWebRTC to send/receive audio/video streams to Amazon Chime SDK meetings.

[What's New](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-chime-sdk-supports-signaling-client-c-plus-plus/) Post

**Comment by raul-guerrero** [comment]
@zhinang-amazon I tried the Signaling client on MacOS both x86_64 and arm64, also on IOS and Android and doesn't build on any of them.
It seems it relies on a library called libwebsockets that needs some major upgrades on both its own code and its dependencies, it uses an almost decade old version of OpenSSL, and uses some really old C and C++ conventions that are now warnings and errors on newer toolchains that being honest I'm not even sure how/why is the signaling client even publicised.

Currently we have a major product on the company I work for that is relying heavily on Chime, and we have 2 desktop apps that need to send video and audio streams to chime to no avail, and is delaying us from delivering, it would be really nice if there was documentation on the Chime signaling sequence and used protocols to at least allow us to implement our own signaling client.

**Comment by hokyungh** [comment]
Hi @raul-guerrero, would you be able to open a new issue for this?

I don't think libwebsockets relies on certain version of openssl. Would you be able to paste what's the command you have tried and openssl version you have linked?
